language: generic

services:
  - redis-server

stages:
  - tests
  - name: apiMerge
    if: branch == master

jobs:
  include:
    - stage: tests
      jdk: "openjdk8"
      script: ./gradlew test
    - stage: apiMerge
      dist: bionic
      python: "3.6.7"
      install: "pip install -r requirements.txt"
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then python autoMerger.py ; fi'
