language: python

install:
  - pip install -r requirements.txt

services:
  - redis-server

stages:
  - tests
  - name: apiMerge
    if: branch == master

jobs:
  include:
    # - stage: tests
    #   script: ./test.sh
    - stage: apiMerge
      python: "3.6"
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then python autoMerger.py ; fi'
