language: python

install:
  - pip install -r requirements.txt

stages:
  - tests
  - name: apiMerge
    if: branch == master

jobs:
  include:
    # - stage: tests
    #   script: ./test.sh
    - stage: apiMerge
      python: "3.6"
      script:
        - python autoMerger.py
