language: java

services:
  - redis-server

stages:
  - tests
  - name: apiMerge
    if: branch == master

jobs:
  include:
    - stage: tests
      jdk: openjdk11
      script: ./gradlew test
      dist: trusty
    - stage: apiMerge
      dist: bionic
      python: "3.6.7"
      env: PYENV_VERSION=3.6.7
      install: "pip3 install -r requirements.txt"
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then python3 autoMerger.py ; fi'
